version: "2"

services:
  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:7.3.1
    mem_limit: 3200m
    environment:
      JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
            "
      JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=secret
                -Dsolr.sharedSecret=dummy
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dcsrf.filter.enabled=false
                -Dimap.server.enabled=false
                -Dftp.enabled=false
                -Xms1g -Xmx3g
                "

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:1.5.3
    mem_limit: 896m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx768m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL : "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8095:8095
    links:
      - activemq

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.6.0
    mem_limit: 1536m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx1536m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8090:8090
    links:
      - activemq

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:1.5.3
    mem_limit: 512m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - 8099:8099
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs

  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432

  solr6:
    image: alfresco/alfresco-search-services:2.0.3
    mem_limit: 2g
    environment:
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: "
          -Dalfresco.secureComms.secret=dummy
        "
    ports:
      - "8083:8983" # Browser port

  activemq:
    image: quay.io/alfresco/alfresco-activemq:5.17.1-jre11-rockylinux8
    mem_limit: 1g
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

  ooi-service:
    image: quay.io/alfresco/alfresco-ooi-service:1.1.3
    mem_limit: 768m
    environment:
      JAVA_OPTS: "
              -Xms256m -Xmx512m
              -Dalfresco.base-url=http://alfresco:8080
              -Dalfresco.deploymodel.enabled=true
              -Dalfresco.deploymodel.timeout=200000
              -Dalfresco.admin.username=admin
              -Dalfresco.admin.password=admin
              "
    ports:
      - 9095:9095

  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:3.1.1
    mem_limit: 128m
    environment:
      BASE_PATH: ./
      APP_CONFIG_PLUGIN_MICROSOFT_ONLINE: 'true'
      APP_CONFIG_MICROSOFT_ONLINE_OOI_URL: https://ttl.dev.alfresco.me/ooi-service/api/-default-/private/office-integration/versions/1/edit-sessions/
      APP_CONFIG_MICROSOFT_ONLINE_CLIENTID: e6738629-4794-47de-86ac-31245842c5c1
      APP_CONFIG_MICROSOFT_ONLINE_AUTHORITY: https://login.microsoftonline.com/aa7f6fe7-d6e9-461c-a718-bebc17ead9b1
      APP_CONFIG_MICROSOFT_ONLINE_REDIRECT: https://ttl.dev.alfresco.me

  proxy:
    image: nginx:stable-alpine
    mem_limit: 256m
    depends_on:
      - alfresco
      - digital-workspace
    ports:
      - 443:443
    links:
      - digital-workspace
      - alfresco
      - ooi-service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem

volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs